### ISSUE TITLE
TestParseTemplateGlob fails intermittently

### ISSUE THREAD

**Issue by asahasrabuddhe** [knadh/stuffbin#6]
The `TestParseTemplateGlob` function intermittently fails with the following error:

![Screenshot 2020-01-22 at 6 31 00 PM](https://user-images.githubusercontent.com/25657923/72896273-5b2dfe00-3d45-11ea-9209-d8eaa1760e6f.png)

The function is not stable as it passes sometimes and fails at other times.

**Comment by asahasrabuddhe** [comment]
I did a little bit of poking around and found that the function `ParseTemplates` accepts multiple paths but chooses only path[0]. Should it not consider all the paths and create a template include all the files in the paths?

**Comment by knadh** [comment]
`template.New(filepath.Base(path[0]))` This is the just the template name. The subsequent loop parses all paths.

https://github.com/knadh/stuffbin/blob/9ba7eec9b8cba4e97f537f462a7577111ae97f57/fs.go#L274

**Comment by asahasrabuddhe** [comment]
Oh yes. I think I found the bug. The thing is we are using a map to store the files in the memFS. In Go, the map does not guarantee order. This causes the assertion to fail as the files do not always follow the order they were added in.

**Comment by asahasrabuddhe** [comment]
I think this got closed with #5
